name: Java jars build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: "Testing a simple script"
      run: echo Hello, world!
    - name: "Make jarfiles"
      run: |
        echo "Running java jarfiles"
        make -C Java/ jarfiles
        echo "Did it work?"
